// Generated by CoffeeScript 1.7.1
module.exports = function(robot) {
  return robot.respond(/qiita new/i, function(msg) {
    return robot.http("https://qiita.com/api/v1/items").get()(function(err, res, body) {
      var article, articles;
      articles = JSON.parse(body);
      article = msg.random(articles);
      msg.send("title:" + article['title']);
      msg.send("url => ");
      msg.send(article['url']);
      return msg.send("author:" + article['user']['url_name']);
    });
  });
};
